# Generated by Django 2.1.7 on 2019-04-01 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=360, unique=True)),
            ],
            options={
                'db_table': 'fortunes',
            },
        ),
    ]
